// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6o9ZkMMDkOqwktkSKk9EiDT9Y9TUd3g',
    appId: '1:337749247346:web:5d645e2f81fc1de21ac9eb',
    messagingSenderId: '337749247346',
    projectId: 'captivate-1dd08',
    authDomain: 'captivate-1dd08.firebaseapp.com',
    storageBucket: 'captivate-1dd08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlyPJ-NFQwAz_v0_FzpG37_zpD1hNne0',
    appId: '1:337749247346:android:da25d765119e1c3c1ac9eb',
    messagingSenderId: '337749247346',
    projectId: 'captivate-1dd08',
    storageBucket: 'captivate-1dd08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1tecf6_8eShHihVb2enqkj_15fxl8zk',
    appId: '1:337749247346:ios:96349685b8fb13e51ac9eb',
    messagingSenderId: '337749247346',
    projectId: 'captivate-1dd08',
    storageBucket: 'captivate-1dd08.appspot.com',
    iosBundleId: 'com.example.captivate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1tecf6_8eShHihVb2enqkj_15fxl8zk',
    appId: '1:337749247346:ios:f598974fc2e04ac01ac9eb',
    messagingSenderId: '337749247346',
    projectId: 'captivate-1dd08',
    storageBucket: 'captivate-1dd08.appspot.com',
    iosBundleId: 'com.example.captivate.RunnerTests',
  );
}
